
services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app:cached
    command: >
      sh -c "npm ci && npm run start:dev"
    # command: ["sh", "-c", "npm run wait-for-mongo && npm run start:dev"]

  mongo:
    image: mongo:6.0
    container_name: nestjs-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongo-express:
    image: mongo-express:1.0
    restart: always
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      # If you enabled authentication on Mongo, set these:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: yourUser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: yourPass
      ME_CONFIG_BASICAUTH_USERNAME: hos      # credentials for mongo-express UI
      ME_CONFIG_BASICAUTH_PASSWORD: hos
  
volumes:
  mongo_data:
